version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=fake-shop
      - POSTGRES_USER=luis
      - POSTGRES_PASSWORD=160598
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=160598
    ports:
      - 5050:80
